# Generated by Django 3.1.7 on 2021-03-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210314_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(max_length=255),
        ),
    ]
