# Generated by Django 3.1.7 on 2021-03-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210314_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
