# Generated by Django 3.1.7 on 2021-03-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210315_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='highlighted',
        ),
    ]
