# Generated by Django 3.1.7 on 2021-03-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
